#!/bin/bash
set -e


#PROFILES=$(aws configure list-profiles)
#REGIONS=$(aws ec2 describe-regions --region us-east-1 | jq -r '.Regions[].RegionName')
REGIONS="us-east-1"
PROFILES=(flow2go)


for PROFILE in "${PROFILES[@]}"; do
  export AWS_PROFILE=${PROFILE}
  for REGION in $REGIONS; do
    for CLUSTER in $(aws eks list-clusters --profile "${PROFILE}" --region "$REGION" | jq -r '.clusters[]'); do
      aws eks update-kubeconfig --region "${REGION}" --name "${CLUSTER}" --alias "${PROFILE}-${CLUSTER}"
    done
  done
done

