#!/bin/bash
set -e

for SUB in $(az account list | jq -rc '.[].id'); do
  az account set --subscription "${SUB}"
  for AKS in $(az aks list --query '[].{name:name,rg:resourceGroup}' | jq -rc '.[]'); do
    AKS_NAME=$(jq -rc '.name' <<< "${AKS}")
    RG_NAME=$(jq -rc '.rg' <<< "${AKS}")
    az aks get-credentials --resource-group "${RG_NAME}" --name "${AKS_NAME}" --overwrite-existing
  done
done

kubelogin convert-kubeconfig -l azurecli