#!/bin/bash
set -e

for SUB in $(az account list | jq -rc '.[]'); do
  SUB_NAME=$(jq -rc '.name' <<< "${SUB}")
  [[ "${SUB_NAME}" =~ "NODIS" ]] && continue
  az account set --name "${SUB_NAME}"
  for AKS in $(az aks list --query '[].{name:name,rg:resourceGroup}' | jq -rc '.[]'); do
    AKS_NAME=$(jq -rc '.name' <<< "${AKS}")
    RG_NAME=$(jq -rc '.rg' <<< "${AKS}")
    az aks get-credentials --subscription "${SUB_NAME}" --resource-group "${RG_NAME}" --name "${AKS_NAME}"
  done
done