#!/bin/bash

PREFIX=terraform-aws
SOURCE=ptonini
DEST=linxsa
FOLDER=${HOME}/Projetos/linxsa/terraform-modules

for R in $(gh search repos --owner "${SOURCE}" "${PREFIX}" --json name -q '.[].name' -L 1000 | grep "${PREFIX}"); do
#  gh repo create "${DEST}/${R}" --internal
  git clone "git@github.com:${SOURCE}/${R}.git"
  (cd "${R}" || exit
  rm -rf .git
  git init && git add . && git commit -m "chore: first commit [skip ci]" && git tag v1.0.0
  git remote add origin "git@github.com:${DEST}/${R}.git"
  git branch -M main
  git push -u origin main
  git push --tags)
  rm -rf "${R}"
  
  # gh variable delete --repo "${R}" vault_k8s_role_path
  # git clone git@github.com:${SOURCE}/${R}.git ${FOLDER}/${R/terraform-/}
  
done
