#!/bin/bash

FOLDER=${HOME}/Projetos/ptonini-actions
ORG=linxsa
PREFIX=${ORG}/terraform-
TF_TOKEN=$(jq -r '.credentials["app.terraform.io"].token' ~/.terraform.d/credentials.tfrc.json)
HEADERS=(--header "Authorization: Bearer $TF_TOKEN" --header "Content-Type: application/vnd.api+json")


#for R in $(gh search repos --owner "${SOURCE}" "${PREFIX}" --json name -q '.[].name' -L 1000 | grep "${PREFIX}"); do
for R in "${FOLDER}"/*; do
  (cd "${R}" || exit

#  [[ -z $(git tag) ]] && pwd && git commit -a --amend -m "chore: first commit" && git push --force

#  PROVIDER=$(basename $R | cut -d- -f 1)
#  MODULE=$(basename $R | cut -d- -f 2-)
#  PAYLOAD="{\"data\":{\"attributes\":{\"vcs-repo\":{\"identifier\":\"${ORG}/terraform-${PROVIDER}-${MODULE}\",\"oauth-token-id\":\"${OAUTH_TOKEN_ID}\",\"display_identifier\":\"${ORG}/terraform-${PROVIDER}-${MODULE}\"},\"no-code\":false},\"type\":\"registry-modules\"}}"

#  echo ${PROVIDER} ${MODULE}
#  echo "${PAYLOAD}" | jq
#  curl "${HEADERS[@]}" --data "${PAYLOAD}" --request POST https://app.terraform.io/api/v2/organizations/${ORG}/registry-modules/vcs



  )
done
