#!/bin/bash

FOLDER=${HOME}/Projetos/linxsa/terraform-modules

for R in $(ls "${FOLDER}"); do
  (cd "${FOLDER}/${R}" || exit
  if [[ $(git tag | wc -l) == 0 ]]; then
    git commit -a --amend -m "chore: first commit [skip ci]"
    git push --force
    git tag v1.0.0
    git push --tags
   fi
  #  for T in $(git tag); do
  #    git tag -d "${T}"
  #    git push --delete origin "${T}"
  #  done
  )
done
