#!/usr/bin/env bash

IFS=$'\n'
for CONTEXT in $(kubectl config get-contexts -o name); do
    kubectl config use "${CONTEXT}"
    for ARGS in $(kubectl get pods --all-namespaces -o json | jq -r '.items[] | select(.status.phase != "Running" and .status.phase != "Pending" and .status.phase != "Succeeded") | [.metadata.name,"-n",.metadata.namespace] | @csv' | sed 's/,/ /g;s/"//g'); do
      if [[ ${DRY_RUN} == "true" ]]; then
        bash -c "kubectl get pod ${ARGS} --no-headers"
      else
        bash -c "kubectl delete pod ${ARGS}"
      fi
    done
done