#!/bin/bash
set -e

UBUNTU_RELEASE=jammy
UBUNTU_VERSION=22.04
NODEJS_VERSION=18
MONGODB_VERSION=6.0
K9_VERSION=0.27.4
KIND_VERSION=0.18.0
COMPASS_VERSION=1.37.0

build_key_name () {
    echo "/usr/share/keyrings/${1}-archive-keyring.gpg"
}

add_source () {
  local NAME="${1}"
  local REPO="${2}"
  local KEY_URL="${3}"
  local KEY="/usr/share/keyrings/${NAME}-archive-keyring.gpg"
  curl -fsSL "${KEY_URL}" | gpg --dearmor | sudo tee "${KEY}" > /dev/null
  echo "deb [arch=amd64 signed-by=${KEY}] ${REPO}" | sudo tee "/etc/apt/sources.list.d/${NAME}.list"
}


if [[ ${1} != "skip_install"  ]]; then

  ### Software installation #############################################################################################

  sudo add-apt-repository -y ppa:git-core/ppa
  sudo add-apt-repository -y universe
  sudo apt-get upgrade -y
  sudo apt-get install -y curl vim jq nmap git remmina-* python3-pip calibre flameshot golang-go lua5.1 luarocks cheese ncdu \
          csvkit make build-essential smartmontools apt-transport-https openssh-server bash-completion libsqlite3-dev gnupg-agent \
          software-properties-common python3-gi python3-gi-cairo gir1.2-gtk-3.0 libbz2-dev libreadline-dev gconf-service \
          liblzma-dev golang-src lsb-release libffi-dev gconf2 libgconf-2-4 libssl-dev gnupg2 zlib1g-dev libgdk-pixbuf2.0-0
  sudo pip3 install --upgrade pipenv ansible openstacksdk

  # APT Repositories
  add_source github-cli "https://cli.github.com/packages stable main" https://cli.github.com/packages/githubcli-archive-keyring.gpg
  add_source azure "https://packages.microsoft.com/repos/azure-cli/ ${UBUNTU_RELEASE} main" https://packages.microsoft.com/keys/microsoft.asc
  add_source google-chrome "https://dl.google.com/linux/chrome/deb/ stable main" https://dl.google.com/linux/linux_signing_key.pub
  add_source google-cloud-packages "https://apt.kubernetes.io/ kubernetes-xenial main stable main" https://packages.cloud.google.com/apt/doc/apt-key.gpg
  add_source google-cloud-k8s "https://packages.cloud.google.com/apt cloud-sdk main" https://packages.cloud.google.com/apt/doc/apt-key.gpg
  add_source helm "https://baltocdn.com/helm/stable/debian/ all main" https://baltocdn.com/helm/signing.asc
  add_source mongodb "https://repo.mongodb.org/apt/ubuntu ${UBUNTU_RELEASE}/mongodb-org/${MONGODB_VERSION} multiverse" "https://www.mongodb.org/static/pgp/server-${MONGODB_VERSION}.asc"
  add_source hashicorp "https://apt.releases.hashicorp.com ${UBUNTU_RELEASE} main" https://apt.releases.hashicorp.com/gpg
  add_source docker "https://download.docker.com/linux/ubuntu ${UBUNTU_RELEASE} stable" https://download.docker.com/linux/ubuntu/gpg
  add_source postgres "https://apt.postgresql.org/pub/repos/apt ${UBUNTU_RELEASE}-pgdg main" https://www.postgresql.org/media/keys/ACCC4CF8.asc
  add_source pgadmin "https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/${UBUNTU_RELEASE} pgadmin4 main" https://www.pgadmin.org/static/packages_pgadmin_org.pub
  add_source spotify "http://repository.spotify.com stable non-free" https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
  add_source virtualbox "https://download.virtualbox.org/virtualbox/debian ${UBUNTU_RELEASE} contrib" https://www.virtualbox.org/download/oracle_vbox_2016.asc
  add_source yarn "https://dl.yarnpkg.com/debian stable main" https://dl.yarnpkg.com/debian/pubkey.gpg
  add_source lens "https://downloads.k8slens.dev/apt/debian stable main" https://downloads.k8slens.dev/keys/gpg

  # Microsoft apt repository
  wget -q "https://packages.microsoft.com/config/ubuntu/${UBUNTU_VERSION}/packages-microsoft-prod.deb"
  sudo apt-get install -y ./packages-microsoft-prod.deb
  rm packages-microsoft-prod.deb*

  # NodeJS
  curl -fsSL "https://deb.nodesource.com/setup_${NODEJS_VERSION}.x" | sudo bash -

  sudo apt-get install -y spotify-client vault pgadmin4 postgresql-client-12 docker-ce nodejs mongodb-database-tools \
          docker-compose terraform azure-cli helm kubectl google-cloud-sdk powershell dotnet-sdk-6.0 mongodb-mongosh \
          google-chrome-stable yarn gh lens aztfexport aztfy virtualbox-7.0

  sudo npm install -g ncc typescript
  sudo npm update -g

  # VSCode
  wget -qO vscode.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
  sudo apt-get install -y ./vscode.deb
  rm vscode.deb*

  # MongoDB Compass
  wget -qO compass.deb "https://downloads.mongodb.com/compass/mongodb-compass_${COMPASS_VERSION}_amd64.deb"
  sudo apt-get install -y ./compass.deb
  rm compass.deb*

  # Rust
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /dev/stdin -y

  # Pyenv
  "${HOME}/.pyenv/bin/pyenv" update || curl -fsSL https://pyenv.run | bash

  # K9s
  wget -q "https://github.com/derailed/k9s/releases/download/v${K9_VERSION}/k9s_Linux_amd64.tar.gz" -O - | sudo tar -C /usr/local/bin/ --overwrite -xzvf - k9s

  # Kind
  sudo wget -qO /usr/local/bin/kind "https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64"
  chmod +x /usr/local/bin/kind

  # AWS CLI
  wget -q https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
  unzip -q awscli-exe-linux-x86_64.zip
  sudo aws/install --update
  rm -rf awscli-exe-linux-x86_64.zip aws/

  # ZeroTier
  curl -fsSL https://install.zerotier.com | sudo bash || true

  sudo apt-get clean

fi

# System configuration ################################################################################################

# System
sudo update-alternatives --set editor /usr/bin/vim.basic

# GIT
git config --global core.editor "vim"
git config --global push.autoSetupRemote true

# GitHub
gh config set git_protocol ssh -h github.com

#touch "${HOME}/.inputrc"
#grep -qxF "set enable-bracketed-paste Off" "${HOME}/.inputrc" || printf "set enable-bracketed-paste Off\n" >> "${HOME}/.inputrc"

BASHRC_STRING="source \${HOME}/.bashrc_custom"
grep -qxF "${BASHRC_STRING}" "${HOME}/.bashrc" || printf "\n%s\n" "${BASHRC_STRING}" >> "${HOME}/.bashrc"

cat << 'EOF' > "${HOME}/.bashrc_custom"
# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Activate pipfile venv
[[ -f ./Pipfile ]] && pipenv shell

# Github
export GH_TOKEN=$(cat "${HOME}/.github_token" 2> /dev/null)

# Kubeconfig
export KUBECONFIG=$HOME/.kube/config
source <(kubectl completion bash)

# Vault
export VAULT_ADDR=https://vault.nodis.com.br

# Terraform
export TF_VAR_kubeconfig=$KUBECONFIG
export TF_VAR_github_token=$GH_TOKEN
export TF_VAR_vault_addr=$VAULT_ADDR

alias tf_fmt='terraform fmt -recursive'
alias tf_get='terraform get'
alias tf_out='terraform output'
alias tf_unlock='terraform force-unlock -force'
alias tf_apply='terraform apply plan'
alias tf_refresh='git pull && tf_fmt && tf_get && terraform plan -parallelism=50 -out=plan'
alias tf_plan='tf_refresh -refresh=false'
alias tf_getup='tf_get -update'
alias tf_kube='tf_out -raw kubeconfig > "${HOME}/.kube/config" && chmod 0600 "${HOME}/.kube/config"'
alias tf_reset='rm -vrf .terraform && terraform init -backend-config=.encryption_key.gcs.tfbackend'

# Golang
export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"

# Lua
export PATH="$HOME/.luarocks/bin:$PATH"

# Kind
source <(kind completion bash)
EOF
source "${HOME}/.bashrc_custom"